name: Send Notification
on:
  pull_request:
    types: [assigned, opened, reopened]

jobs:
  notification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Send Notification
        uses: stvenx/wechat-work-messenger@master
        env:
          BOT_KEY: ${{ secrets.BOT_KEY }}
          PHONE_MAPS: ${{ secrets.PHONE_MAPS }}
          MSG_TYPE: text
          POST_MESSAGE: |
            ### 收到新的 PR \n
            > 创建者：  ${{ github.event.pull_request.user.login }} \n
            > PR 标题： ${{ github.event.pull_request.title }}  \n
            > PR 地址： ${{ github.event.pull_request.html_url }}  \n
            > 项目地址： ${{ github.event.repository.html_url }}/actions \n
          ASSIGNEES: ${{ toJson(github.event.pull_request.assignees) }}

